name:                userProject
version:             0.1.0.0
github:              "githubuser/userProject"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/userProject#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- utf8-string
- warp
- postgresql-simple
- servant-swagger
- swagger2
- text
- directory
- servant-multipart
- bytestring
- req
- time
- resource-pool
- http-client
- transformers
- utf8-string
- containers

library:
  source-dirs: src

executables:
  userProject-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - userProject

tests:
  userProject-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - userProject
    - hspec
    - hspec-wai
    - directory
    - hspec-wai-json
    - aeson
    - postgresql-simple
    - servant-swagger
    - swagger2
    - text
    - req
    - time
    - containers
    - resource-pool
    - utf8-string
    - utf8-string
    - servant-multipart
    - bytestring
    - http-client
    - transformers
