name:                g10x-ecomm-logic-prototype
version:             0.1.0.0
github:              "githubuser/g10x-ecomm-logic-prototype"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/g10x-ecomm-logic-prototype#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- servant-server
- wai
- warp
- time
- text
- bytestring
- servant-auth-server
- resource-pool
- postgresql-simple
- containers
- exceptions
- transformers
- mtl
- http-types
- unliftio
- servant
- servant-auth-server
- text
- monad-time
- time
- directory


library:
  source-dirs: src

executables:
  g10x-ecomm-logic-prototype-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - g10x-ecomm-logic-prototype
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - text
    - bytestring
    - servant-auth-server
    - resource-pool
    - postgresql-simple
    - containers
    - exceptions
    - transformers
    - mtl
    - http-types
    - unliftio
    - servant
    - text
    - monad-time


tests:
  g10x-ecomm-logic-prototype-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - g10x-ecomm-logic-prototype
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
    - text
    - bytestring
    - servant-auth-server
    - monad-time
    - containers
    - resource-pool
    - postgresql-simple
    - monad-time

    
