version: "3.9"  # optional since v1.27.0
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment :
      POSTGRES_PASSWORD : "${dbpasw}"

  server :
    build: 
      context : .
      args : 
        - {buildargs}
    ports:
      - "8080:8080"
    depends_on : 
      - postgres
    environment:
      CONFIG : ${config}
    
 
